"""empty message

Revision ID: 68f91cd0b91d
Revises: 
Create Date: 2021-04-24 17:24:50.376697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f91cd0b91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trademarks',
    sa.Column('app_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owners', sa.String(), nullable=True),
    sa.Column('applicant', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('trademark_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_no')
    )
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_no', sa.Integer(), nullable=True),
    sa.Column('class_spec', sa.String(), nullable=True),
    sa.Column('tm_app_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tm_app_no'], ['trademarks.app_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specs')
    op.drop_table('trademarks')
    # ### end Alembic commands ###
